version: "3.7"

services:

  nginx:
    container_name: nginx_codo
    image: nginx:latest
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8181:8181" 
    networks:
      - larara_net
    restart: always

  codosasa:
    container_name: codocont
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - larara_net
    restart: always


networks:
  larara_net:
    driver: bridge



