version: "3.7"

services:

  nginx:
    container_name: nginx_container
    image: nginx:latest
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8547:8547" 
    networks:
      - lara_net
    restart: always

  laravelsasa:
    container_name: laracontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - lara_net
    restart: always


networks:
  lara_net:
    driver: bridge

# Volumes
# volumes:
#   mssqldata:
#     driver: local



